### ISSUE TITLE
Gotta be honest

### ISSUE THREAD

**Issue by benzon** [Canderson8495/Erryial_Wine#1]
It's a joy when new devs release things.

But it's a shame when they based there script on something that was made wrong in every single way to start of with.

This part alone is fucked up NOTHING and i repeat my self NOTHING should be made in this way where you spam a Trigger.

This should be done with a loop insted, that generates the pickup blips, and deffently not by spamming it this amount of times.

And from just looking thrue the code i can only imagine how bad the ms tick on this resource is.

It's a shame you based your script on his code, because it could have been rly good.
```
Citizen.CreateThread( function()
    Citizen.Wait(10000)

    while true do
    Citizen.Wait(1000)
        if GetDistanceBetweenCoords(Config.PickupBlip.x,Config.PickupBlip.y,Config.PickupBlip.z, GetEntityCoords(GetPlayerPed(-1))) <= 200 then
            if spawned == false then
                TriggerEvent('EWine:start')
                TriggerEvent('EWine:start')
                TriggerEvent('EWine:start')
                TriggerEvent('EWine:start')
                TriggerEvent('EWine:start')
                TriggerEvent('EWine:start')
                TriggerEvent('EWine:start')
                TriggerEvent('EWine:start')
                TriggerEvent('EWine:start')
                TriggerEvent('EWine:start')
                TriggerEvent('EWine:start')
            end
            spawned = true
        else
            if spawned then
                locations = {}
            end
            spawned = false
            
        end
    end
end)
```

**Comment by Canderson8495** [comment]
As I recall the tick time was not high(~.1?), and it’s also important to understand that this was one of the final scripts that were created by Blue Sky RP, and it did not receive any optimizations. I understand that shortcuts were taken in the code, but this script was created in less than 4 hours. I highly welcome any contributions that are in the interest of the open source community, so that we can allow the eco system of free FiveM scripts flourish.

Thank you for your input.
